name: simple test suite on macOS

on:
  push:
    branches:
      - 'next-macos'

jobs:
  darwin-x64-test:
    runs-on: macOS-13
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install dependencies
        run: |
          cd /Users/runner/work/gild-cli/gild-cli/main
          bun install

      - name: run tests
        run: |
          cd /Users/runner/work/gild-cli/gild-cli/main
          bun test --coverage

  darwin-arm64-test:
    runs-on: macOS-latest 
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install dependencies
        run: |
          cd /Users/runner/work/gild-cli/gild-cli/main
          bun install

      - name: run tests
        run: |
          cd /Users/runner/work/gild-cli/gild-cli/main
          bun test --coverage